### ISSUE TITLE
Event summary null

### ISSUE THREAD

**Issue by pmagnuson** [dart-lang/googleapis#151]
The following code (Dart) is used to retrieve calendar data:
```dart
void main() {
  print('Calendar test');
  clientViaServiceAccount(_credentials, _SCOPES).then((http_client) {
    var calendar = CalendarApi(http_client);

    var event = calendar.events;
    calendar.calendarList.list().then((CalendarList element) {
      print(element.toJson());
    });

    event.list('xxxxx@yyyyy.org').then((showEvents) {
      print('event count = ${showEvents.items.length}');
      print('showEvents= ${showEvents.toJson()}');
      showEvents.items.forEach((Event ev) {
        print('event= ${ev.toJson()}');
        print('summary: ${ev.summary}');
        print('description: ${ev.description}');
      });
    });
  });
}
```
The result is returned successfully
```yaml
{
  accessRole: freeBusyReader, 
  defaultReminders: [], 
  etag: "p33o851siuf7es0g", 
  items: [
    {
      end: {dateTime: 2021-02-03T18:00:00.000Z}, 
      etag: "3224791795058000", 
      htmlLink: https://www.google.com/calendar/event?eid=N2U5ZGQ0bzFhNmE1MmZ2OWlzY29tZjBoYWcgcGhpbC5tYWdudXNvbkB0aGVidWRkaGFwYXRoLm9yZw, 
      iCalUID: 7e9dd4o1a6a52fv9iscomf0hag@google.com, 
      id: 7e9dd4o1a6a52fv9iscomf0hag, 
      kind: calendar#event, 
      start: {dateTime: 2021-02-03T17:00:00.000Z}, 
      status: confirmed, 
      updated: 2021-02-03T23:44:57.529Z, visibility: private
    }, 
    {
      end: {dateTime: 2021-02-04T18:00:00.000Z}, 
      etag: "3224791981196000", 
      htmlLink: https://www.google.com/calendar/event?eid=NWRlZnBtaGd2ZnM1aW41Y2ZjbDh1cHFibWcgcGhpbC5tYWdudXNvbkB0aGVidWRkaGFwYXRoLm9yZw, 
      iCalUID: 5defpmhgvfs5in5cfcl8upqbmg@google.com, 
      id: 5defpmhgvfs5in5cfcl8upqbmg, 
      kind: calendar#event, 
      start: {dateTime: 2021-02-04T17:00:00.000Z}, 
      status: confirmed, 
      updated: 2021-02-03T23:46:30.598Z, visibility: private
    }
  ], 
  kind: calendar#events, 
  nextSyncToken: CPCCh5Lzzu4CEPCCh5Lzzu4CGAo=,  
  summary: xxxxx@yyyyy.org,  
  timeZone: America/Boise,  
  updated: 2021-02-03T23:46:30.598Z}
```

Neither if the event items contains the `summary` or `description`

Both of these fields are returned successfully when using the **Try this API** at developers.google.com
```yaml
{
 "kind": "calendar#events",
 "etag": "\"p33o851siuf7es0g\"",
 "summary": "xxxxx@yyyyy.org",
 "updated": "2021-02-03T23:46:30.598Z",
 "timeZone": "America/Boise",
 "accessRole": "owner",
 "defaultReminders": [
  {
   "method": "popup",
   "minutes": 10
  }
 ],
 "nextSyncToken": "CPCCh5Lzzu4CEPCCh5Lzzu4CGAU=",
 "items": [
  {
   "kind": "calendar#event",
   "etag": "\"3224791795058000\"",
   "id": "7e9dd4o1a6a52fv9iscomf0hag",
   "status": "confirmed",
   "htmlLink": "https://www.google.com/calendar/event?eid=N2U5ZGQ0bzFhNmE1MmZ2OWlzY29tZjBoYWcgcGhpbC5tYWdudXNvbkB0aGVidWRkaGFwYXRoLm9yZw",
   "created": "2021-02-03T17:55:25.000Z",
   "updated": "2021-02-03T23:44:57.529Z",
   "summary": "Event name",
   "description": "This is the description",
   "location": "location",
   "creator": {
    "email": "xxxxx@yyyyy.org",
    "self": true
   },
   "organizer": {
    "email": "xxxxx@yyyyy.org",
    "self": true
   },
   "start": {
    "dateTime": "2021-02-03T10:00:00-07:00"
   },
   "end": {
    "dateTime": "2021-02-03T11:00:00-07:00"
   },
   "iCalUID": "7e9dd4o1a6a52fv9iscomf0hag@google.com",
   "sequence": 0,
   "reminders": {
    "useDefault": true
   },
   "eventType": "default"
  },
  {
   "kind": "calendar#event",
   "etag": "\"3224791981196000\"",
   "id": "5defpmhgvfs5in5cfcl8upqbmg",
   "status": "confirmed",
   "htmlLink": "https://www.google.com/calendar/event?eid=NWRlZnBtaGd2ZnM1aW41Y2ZjbDh1cHFibWcgcGhpbC5tYWdudXNvbkB0aGVidWRkaGFwYXRoLm9yZw",
   "created": "2021-02-03T23:46:19.000Z",
   "updated": "2021-02-03T23:46:30.598Z",
   "summary": "Event two",
   "description": "This is the description",
   "location": "location",
   "creator": {
    "email": "xxxxx@yyyyy.org",
    "self": true
   },
   "organizer": {
    "email": "xxxxx@yyyyy.org",
    "self": true
   },
   "start": {
    "dateTime": "2021-02-04T10:00:00-07:00"
   },
   "end": {
    "dateTime": "2021-02-04T11:00:00-07:00"
   },
   "iCalUID": "5defpmhgvfs5in5cfcl8upqbmg@google.com",
   "sequence": 0,
   "reminders": {
    "useDefault": true
   },
   "eventType": "default"
  }
 ]
}
```
