### ISSUE TITLE
Error running googleapi on flutter

### ISSUE THREAD

**Issue by eugenio-tesio** [dart-lang/googleapis#35]
I run the example in flutter and i get an error:

```
import 'package:googleapis/storage/v1.dart';
import 'package:googleapis_auth/auth_io.dart';

final _credentials = new ServiceAccountCredentials.fromJson(r'''
{
  "private_key_id": ...,
  "private_key": ...,
  "client_email": ...,
  "client_id": ...,
  "type": "service_account"
}
''');

const _SCOPES = const [StorageApi.DevstorageReadOnlyScope];

void main() {
  clientViaServiceAccount(_credentials, _SCOPES).then((http_client) {
    var storage = new StorageApi(http_client);
    storage.buckets.list('dart-on-cloud').then((buckets) {
      print("Received ${buckets.items.length} bucket names:");
      for (var file in buckets.items) {
        print(file.name);
      }
    });
  });
}
```

E/flutter (  752): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (  752): type '_InternalLinkedHashMap' is not a subtype of type 'Map<String, List<String>>' where
E/flutter (  752):   _InternalLinkedHashMap is from dart:collection
E/flutter (  752):   Map is from dart:core
E/flutter (  752):   String is from dart:core
E/flutter (  752):   List is from dart:core
E/flutter (  752):   String is from dart:core

This is my pubspec.yaml:

```
name: consumos_app
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.0
  path_provider: ^0.3.1
  json_annotation: ^0.2.2
  shared_preferences: "^0.3.3"
  intl: "^0.15.2"
  googleapis: "^0.50.0"
  googleapis_auth: "^0.2.5"

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^0.7.6
  json_serializable: ^0.3.2

flutter:
  uses-material-design: true
```
